CREATE TABLE IF NOT EXISTS users (
    id          BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    email       TEXT        NOT NULL UNIQUE,
    name        VARCHAR        NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);